package at.itb13.oculus.presentation;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import at.itb13.oculus.lang.Lang;
import at.itb13.oculus.lang.LangFacade;
import at.itb13.oculus.lang.LangKey;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.event.ActionEvent;
import javafx.scene.control.MenuItem;
import javafx.scene.control.Label;
import javafx.scene.control.RadioButton;
import javafx.scene.control.Menu;

public class CreateNewPatientGUIController implements Initializable {
	@FXML
	private Menu _file;
	@FXML
	private MenuItem _close;
	@FXML
	private Menu _language;
	@FXML
	private MenuItem _english;
	@FXML
	private MenuItem _german;
	@FXML
	private Menu _help;
	@FXML
	private MenuItem _about;
	@FXML
	private Label _firstname;
	@FXML
	private Label _gender;
	@FXML
	private Label _country;
	@FXML
	private Label _socialsecuritynumber;
	@FXML
	private Label _street;
	@FXML
	private Label _birthday;
	@FXML
	private Label _zip;
	@FXML
	private Label _streetnumber;
	@FXML
	private RadioButton _female;
	@FXML
	private RadioButton _male;
	@FXML
	private Label _email;
	@FXML
	private Label _employer;
	@FXML
	private Label _phonenumber;
	@FXML
	private Label _lastname;
	@FXML
	private Button _saveButton;
	@FXML
	private Button _clearButton;

	// Event Listener on MenuItem[#_close].onAction
	@FXML
	public void close(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#_english].onAction
	@FXML
	public void changeToEnglish(ActionEvent event) {
		System.out.println("English");
		try {	
			LangFacade.load(Lang.ENGLISH);
			LangFacade facade = LangFacade.getInstance();
			changeLanguage(facade);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	// Event Listener on MenuItem[#_german].onAction
	@FXML
	public void changeToGerman(ActionEvent event) {
		System.out.println("German");
		try {	
			LangFacade.load(Lang.GERMAN);
			LangFacade facade = LangFacade.getInstance();
			changeLanguage(facade);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#_saveButton].onAction
	@FXML
	public void save(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#_clearButton].onAction
	@FXML
	public void clear(ActionEvent event) {
		// TODO Autogenerated
	}
	
	private void changeLanguage(LangFacade facade){
		
		_firstname.setText(facade.getString(LangKey.FIRSTNAME));
		_lastname.setText(facade.getString(LangKey.LASTNAME));
		_birthday.setText(facade.getString(LangKey.BIRTHDAY));
		_gender.setText(facade.getString(LangKey.GENDER));
		_male.setText(facade.getString(LangKey.MALE));
		_female.setText(facade.getString(LangKey.FEMALE));
		_phonenumber.setText(facade.getString(LangKey.PHONENUMBER));
		_email.setText(facade.getString(LangKey.EMAIL));
		_zip.setText(facade.getString(LangKey.ZIPCODE));
		_country.setText(facade.getString(LangKey.COUNTRY));
		_street.setText(facade.getString(LangKey.STREET));
		_streetnumber.setText(facade.getString(LangKey.STREETNUMBER));
		_socialsecuritynumber.setText(facade.getString(LangKey.SOCIALSECURITYNUMBER));
		_employer.setText(facade.getString(LangKey.EMPLOYER));
		_saveButton.setText(facade.getString(LangKey.SAVE));
		_clearButton.setText(facade.getString(LangKey.CLEAR));
		
		
		_file.setText(facade.getString(LangKey.FILE));
		_close.setText(facade.getString(LangKey.EXIT));
		_language.setText(facade.getString(LangKey.LANGUAGE));
		_german.setText(facade.getString(LangKey.GERMAN));
		_english.setText(facade.getString(LangKey.ENGLISH));
		_help.setText(facade.getString(LangKey.HELP));
		_about.setText(facade.getString(LangKey.ABOUT));
		
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		
	}
}
