package at.itb13.oculus.presentation;

import javafx.fxml.FXML;
import javafx.event.ActionEvent;
import javafx.scene.control.MenuItem;

public class MainView {

	@FXML
	private MenuItem _closeItem;
	@FXML
	private MenuItem _deleteItem;
	@FXML
	private MenuItem _aboutItem;


	// Event Listener on MenuItem[#_closeItem].onAction
	@FXML
	public void closeApplication(ActionEvent event) {
		
	}
	// Event Listener on MenuItem[#_aboutItem].onAction
	@FXML
	public void openAboutDialog(ActionEvent event) {
		// TODO Autogenerated
	}
}
