package at.itb13.oculus.presentation;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.event.ActionEvent;
import javafx.scene.control.MenuItem;

public class PatientMainViewController  {

	@FXML
	private MenuItem _closeItem;
	@FXML
	private MenuItem _deleteItem;
	@FXML
	private MenuItem _aboutItem;
	@FXML
	private PatientTabViewController _patientTabViewController;


	// Event Listener on MenuItem[#_closeItem].onAction
	@FXML
	public void closeApplication(ActionEvent event) {
		
	}
	// Event Listener on MenuItem[#_aboutItem].onAction
	@FXML
	public void openAboutDialog(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void initialize(){
		
		System.out.println("MAINVIEW");
		//_patientTabViewController.init(this);
	}
	
	
	public void init(PatientTabViewController patientTabViewController) {
		_patientTabViewController = patientTabViewController;
	}
}
