package at.itb13.oculus.presentation;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.MenuItem;
import javafx.scene.input.MouseEvent;

public class PatientMainViewController implements Initializable  {

	//child - PatientTabViewController
	@FXML
	private PatientTabViewController _patientTabViewController;
	@FXML
	private MenuItem _closeItem;
	@FXML
	private MenuItem _deleteItem;
	@FXML
	private MenuItem _aboutItem;
	@FXML
	private QueueViewController _queueViewController;
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		_patientTabViewController.init(this);			
	}
	
	// Event Listener on MenuItem[#_closeItem].onAction
	@FXML
	public void closeApplication(ActionEvent event) {
		
	}
	// Event Listener on MenuItem[#_aboutItem].onAction
	@FXML
	public void openAboutDialog(ActionEvent event) {
		// TODO Autogenerated
	}
	@FXML
	public void openTreatmentView(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#_calendarButton].onDragDetected
	@FXML
	public void openCalendarView(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#_patientView].onAction
	@FXML
	public void openPatientView(ActionEvent event) {
		// TODO Autogenerated
	}
	//init child - PatientTabViewController
	public void init(PatientTabViewController patientTabViewController) {
		_patientTabViewController = patientTabViewController;
	}
}
